updated code to handle incremental version

diff --git a/.github/workflows/buildMain.yaml b/.github/workflows/buildMain.yaml
--- a/.github/workflows/buildMain.yaml
+++ b/.github/workflows/buildMain.yaml
@@ -29,8 +29,14 @@ jobs:
         id: image_version
         run: |
           IMAGE_TAG=$(bash scripts/next-image-version.sh)
-          echo "tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
+
+          if [ -z "${IMAGE_TAG}" ]; then
+            echo "ERROR: IMAGE_TAG is empty"
+            exit 1
+          fi
+
           echo "IMAGE_TAG=${IMAGE_TAG}"
+          echo "tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
 
       - name: Build
         run: mvn clean install
